# Generated by Django 5.0.2 on 2024-02-15 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10)),
                ('apellidos', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('direccion_domiciliaria', models.TextField()),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1, null=True)),
                ('correo_electronico', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_sangre', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('certificado_votacion', models.BooleanField()),
                ('cargas_familiares', models.IntegerField()),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('discapacidad', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Capacidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_estudio', models.CharField(choices=[('Primario', 'Primario'), ('Secundario', 'Secundario'), ('Bachiller EN CURSO', 'Bachiller EN CURSO'), ('Bachiller', 'Bachiller'), ('Universitario EN CURSO', 'Universitario EN CURSO'), ('Universitario', 'Universitario'), ('Magister', 'Magister')], max_length=50)),
                ('num_escuela_capacitacion', models.CharField(max_length=20)),
                ('licencia_conducir', models.BooleanField()),
                ('tipo_licencia', models.CharField(blank=True, choices=[('No Aplica', 'No Aplica'), ('Tipo B', 'Tipo B (solo autos)'), ('Tipo Moto', 'Tipo Moto'), ('Tipo Profesional', 'Tipo Profesional')], default='No Aplica', max_length=30, null=True)),
                ('record', models.BooleanField()),
                ('certificado_salud', models.BooleanField()),
                ('afis', models.BooleanField()),
                ('cursos_seguridad', models.TextField(blank=True, max_length=50, null=True)),
                ('libreta_militar', models.BooleanField()),
                ('datos_personales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guardias.datospersonales')),
            ],
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('puesto_asignado', models.CharField(blank=True, max_length=40, null=True)),
                ('Descripcion_puesto', models.TextField(blank=True, max_length=100, null=True)),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('razon_salida', models.TextField(blank=True, max_length=100, null=True)),
                ('datos_personales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guardias.datospersonales')),
            ],
        ),
    ]
